<?php

namespace App\Services;

use App\Models\Interest;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

/**
 * إنشاء مستند الاتفاق PDF — SRS-F08-05 · UC-07.
 * مستند ثابت بأسماء الطرفين يُنشأ عند القبول خلال < 5 ثوانٍ ويُحفظ في storage/app/public/agreements/.
 *
 * ملاحظة: PDF مبني يدوياً (Helvetica) — يدعم الأسماء اللاتينية/الرقمية فقط في MVP.
 * دعم النص العربي الكامل يتطلب محرك PDF بخطوط عربية (dompdf + خط عربي) — مؤجل v1.1.
 */
class AgreementPdfService
{
    public function generate(Interest $interest): string
    {
        $project = $interest->project;
        $owner = $project->owner;
        $investor = $interest->investor;

        $lines = [
            'Ihyaa (Ihyaa) - Simple Agreement',
            '==============================',
            'Date: '.now()->format('Y-m-d H:i'),
            '',
            'Project: '.$this->sanitize($project->title),
            'Project ID: '.$project->id,
            '',
            'Idea Owner: '.$this->sanitize($owner->name),
            'Owner Email: '.$this->sanitize($owner->email),
            'Investor: '.$this->sanitize($investor->name),
            'Investor Email: '.$this->sanitize($investor->email),
            '',
            'Interest Type: '.$interest->interest_type->value,
            'Interest ID: '.$interest->id,
            '',
            'This document confirms that the investor expressed interest in the project',
            'and the idea owner accepted it on the Ihyaa platform.',
            'Detailed legal terms are deferred to a full agreement (v2.0+).',
            '',
            'Generated by Ihyaa Platform - '.__('app.name', [], 'ar'),
        ];

        $pdf = $this->buildPdf(implode("\n", $lines));

        $fileName = 'agreement-'.$interest->id.'-'.Str::uuid()->toString().'.pdf';
        $path = 'agreements/'.$fileName;

        Storage::disk('public')->put($path, $pdf);

        return $path;
    }

    /** الأسماء تُنقّى من المحارف غير المدعومة في Helvetica (العربية تُستبدل بنص محايد) */
    protected function sanitize(string $value): string
    {
        $clean = preg_replace('/[^\x20-\x7E]/u', '', $value);

        return trim($clean) !== '' ? $clean : '[Unicode name omitted]';
    }

    // ——————————————————————— بناء PDF صالح (حد أدنى) ———————————————————————

    /** بناء PDF نصي بسيط (يُستخدم للاتفاق وتصدير التقرير) */
    public function buildPdf(string $text): string
    {
        $objects = [];

        $objects[1] = '<< /Type /Catalog /Pages 2 0 R >>';
        $objects[2] = '<< /Type /Pages /Kids [3 0 R] /Count 1 >>';
        $objects[3] = '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] '
            .'/Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>';
        $objects[4] = $this->buildContentStream($text);
        $objects[5] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';

        $parts = [];
        $offset = 0;
        $offsets = [0];

        for ($id = 1; $id <= count($objects); $id++) {
            $offsets[$id] = $offset;
            $chunk = $id." 0 obj\n".$objects[$id]."\nendobj\n";
            $parts[] = $chunk;
            $offset += strlen($chunk);
        }

        $xrefStart = $offset;
        $xref = "xref\n0 ".(count($objects) + 1)."\n";
        $xref .= "0000000000 65535 f \n";
        for ($id = 1; $id <= count($objects); $id++) {
            $xref .= sprintf("%010d 00000 n \n", $offsets[$id]);
        }

        $trailer = "trailer\n<< /Size ".(count($objects) + 1)." /Root 1 0 R >>\n"
            ."startxref\n{$xrefStart}\n%%EOF";

        return "%PDF-1.4\n".implode('', $parts).$xref.$trailer;
    }

    protected function buildContentStream(string $text): string
    {
        $stream = "BT\n/F1 11 Tf\n50 780 Td\n16 TL\n";
        $lines = explode("\n", $text);

        foreach ($lines as $index => $line) {
            $escaped = str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], $line);
            $stream .= '('.$escaped.') Tj'.($index < count($lines) - 1 ? "\nT*" : '');
        }

        $stream .= "\nET";

        return '<< /Length '.strlen($stream)." >>\nstream\n".$stream."\nendstream";
    }
}
